graphql-plugin-getters.js
src/components/HOCs/withIntl.spec.tsx
src/components/molecules/playlistButton.tsx
src/components/organisms/header.tsx
src/containers/account/register.spec.tsx
src/containers/account/register.tsx

Accidentally merged previous PR prematurely, so had to create another one to get changes from your review in

Register code review fixes

---

.storybook/webpack.config.js
jest.config.js
package-lock.json
package.json

DRY tsconfig paths

---

src/components/molecules/card/bibleBook.module.scss
src/components/molecules/card/collection.module.scss
src/components/molecules/card/hat/index.module.scss
src/components/molecules/card/person.module.scss
src/components/molecules/card/playlist.module.scss
src/components/molecules/card/post.module.scss
src/components/molecules/card/sequence.module.scss
src/components/molecules/card/sponsor.module.scss
src/components/molecules/circleButton.module.scss
src/components/molecules/namedAvatar.module.scss
src/components/molecules/teaseRecording.module.scss
src/components/organisms/navigation.module.scss
src/components/organisms/navigation.spec.tsx
src/components/organisms/navigation.tsx
src/containers/base.tsx
src/containers/library/history.graphql
src/containers/library/history.module.scss
src/containers/library/history.tsx
src/containers/library/playbackStatus.tsx
src/containers/presenter/list.module.scss
src/containers/sponsor/list.module.scss
src/lib/generated/graphql.ts
src/styles/styles.scss

Fixes https://trello.com/c/EMktF8p6/145-fix-ivy-font-missing-in-safari, https://trello.com/c/A0sNIEl1/135-apply-background-color-transition-globally, https://trello.com/c/FVmspAw6/92-add-infinite-scrolling, https://trello.com/c/CiXLLJDz/147-fix-overflow-issue-on-navigation-donate-button.

Fix visual bugs

---

src/__mocks__/next/image.tsx
src/components/atoms/roundImage.tsx

Refs (and hopefully fixes) https://trello.com/c/vXB3CWOg/152-vercel-image-optimization-limit.

Un-optimize rounded images for Vercel

---

src/components/molecules/card/post.module.scss
src/components/molecules/card/post.spec.tsx
src/components/molecules/card/post.tsx
src/components/organisms/section.module.scss
src/components/organisms/section.tsx
src/components/organisms/slider.module.scss
src/components/organisms/slider.tsx
src/components/organisms/testimonies.module.scss
src/components/templates/andNavigation.module.scss
src/containers/home.module.scss
src/containers/home.tsx
src/pages/[language]/give.tsx

Finishes https://trello.com/c/Tbo57Qi2/150-pre-beta-home-page-adjustments, https://trello.com/c/O327hGPC/168-tweak-blog-post-card.

First pass at mobile home page

---

src/containers/account/register.spec.tsx
src/containers/account/register.tsx

Should finish https://trello.com/c/q5KRqv2v/71-registration-flow.

Redirect on register or logged in

---

src/containers/home.module.scss

Fixes https://trello.com/c/ci3GlfW0/143-is-carousel-transition-flash-intended.

Smooth slideshow transition

---

src/components/molecules/buttonPlay.tsx
src/components/molecules/player.tsx
src/components/molecules/teaseRecording.tsx
src/components/organisms/recording.tsx
src/components/templates/andMiniplayer.tsx
src/containers/base.tsx
src/containers/bible/book.tsx
src/lib/api/useIsFavorited.ts
src/lib/api/useIsRecordingFavorited.ts
src/lib/usePlaybackSession.tsx

Fixes https://trello.com/c/r1r3LZLT/100-playlist-playing.

Autoplay audiobooks, audio Bibles, and music

---

schema.graphql
src/components/molecules/card/post.module.scss
src/components/molecules/form/textarea.module.scss
src/components/molecules/form/textarea.tsx
src/components/organisms/testimonies.module.scss
src/components/organisms/testimonies.tsx
src/containers/blog/detail.module.scss
src/containers/contact.graphql
src/containers/contact.module.scss
src/containers/contact.tsx
src/containers/home.module.scss
src/containers/testimonies.tsx
src/lib/generated/graphql.ts
src/pages/[language]/contact/[type].ts

Depends on https://github.com/avorg/audioverse-graphql/pull/468 and fixes https://trello.com/c/gfbfmqUp/60-submit-testimony, https://trello.com/c/d42Dvd0f/171-contact-forms.

Add support for contact/testimonial forms

---

src/components/atoms/progressBar.module.scss
src/components/atoms/progressBar.tsx
src/components/molecules/player.module.scss
src/components/molecules/player.tsx
src/components/molecules/recordingProgressBar.tsx
src/components/templates/andMiniplayer.tsx
src/lib/test/helpers.tsx
src/lib/usePlaybackSession.tsx

Fixes https://trello.com/c/M37R6T8k/108-player-buffer-indicator.

Add player buffer indicators

---

src/containers/home.tsx

Fixes https://trello.com/c/VrqlmzgR/184-clean-up-non-english-home-pages.

Tweak non-English home page

---

src/containers/home.tsx

Fixes https://trello.com/c/qkfXP0PO/185-link-on-home-page-not-formatted-until-hovered.

Fix undecorated link

---

.gitignore
src/components/molecules/buttonSpeed.tsx
src/components/molecules/player.spec.tsx

Requested by user, Alistair said it's fine to add back.

Add 1.25x speed back in

---

public/compiled-lang/en.json
public/lang/en.json
src/components/molecules/mininav.module.scss
src/components/molecules/mininav.tsx
src/components/molecules/personTypeLockup.tsx
src/components/molecules/teaseRecording.tsx
src/components/organisms/libraryNav.module.scss
src/components/organisms/section.module.scss
src/components/organisms/section.tsx
src/components/organisms/slider.module.scss
src/components/organisms/slider.tsx
src/components/organisms/testimonies.module.scss
src/components/templates/andNavigation.module.scss
src/components/templates/andNavigation.tsx
src/containers/collection/detail.tsx
src/containers/collection/presenters.tsx
src/containers/discover/collections.tsx
src/containers/home.module.scss
src/containers/home.tsx
src/containers/library/collections.tsx
src/containers/presenter/list.spec.tsx
src/containers/presenter/list.tsx
src/containers/search/index.tsx
src/lib/getNavigationItems.tsx
src/lib/routes.ts

Fixes https://trello.com/c/7QU1a5tw/197-footer-alignment-seems-like-it-needs-work-on-mobile, https://trello.com/c/UwkNRWTm/196-hide-bible-for-non-english-sites, https://trello.com/c/SgdcfzGS/194-add-current-tab-indication-on-mobile-subnav, https://trello.com/c/Jkonx8st/193-logged-out-library-padding-funny, https://trello.com/c/LFMA1S9K/191-add-search-to-discover-on-mobile, https://trello.com/c/BUsfEMVv/198-use-presenters-term, https://trello.com/c/USdD96HQ/146-home-page-tablet-viewport.

Tweaks and fixes

---

next.config.js
package-lock.json
package.json

Add support to analyze bundles

---

src/components/HOCs/withIntl.tsx
src/components/organisms/aboutNav.tsx
src/components/organisms/navigation.tsx
src/components/templates/andNavigation.tsx
src/containers/account/playlists.spec.tsx
src/containers/base.media.spec.tsx
src/containers/base.spec.tsx
src/lib/generateFeed.spec.ts
src/lib/generateFeed.ts
src/lib/getIntl.ts
src/lib/getIntlMessages.ts
src/lib/getNavigationItems.tsx
src/lib/test/helpers.tsx
src/pages/[language]/books/[id]/feed.xml/index.ts
src/pages/[language]/presenters/[id]/feed.xml/index.ts
src/pages/[language]/sponsors/[id]/teachings/feed.xml/index.ts
src/pages/[language]/stories/albums/[id]/feed.xml/index.ts
src/pages/[language]/teachings/all/feed.xml/index.ts

Codesplit intl messages

---

src/components/molecules/player.spec.tsx
src/components/organisms/miniplayer.tsx
src/components/templates/andPlaybackContext.tsx
src/containers/bible/book.spec.tsx
src/containers/sermon/detail.spec.tsx

Lazy load video.js

---

src/containers/home.tsx

Make home hero image priority for LCP

---

.eslintrc.js
lang-extract-new.js
package-lock.json
package.json
src/__mocks__/next/image.tsx
src/components/molecules/card/songBook.tsx
src/components/molecules/copyrightInfos.tsx
src/components/molecules/socialLogin.tsx
src/components/organisms/recording.tsx
src/components/templates/andPlaybackContext.tsx
src/containers/account/playlists.spec.tsx
src/containers/account/preferences.tsx
src/containers/account/profile.spec.tsx
src/containers/search/index.tsx
src/containers/song/books/detail.tsx
src/lib/api/bibleBrain.ts
src/lib/api/fetchApi.spec.ts
src/lib/api/useAddPlaylist.ts
src/lib/cookies.ts
src/lib/getDetailStaticPaths.tsx
src/lib/getIntlMessages.spec.ts
src/lib/getLanguageByBaseUrl.ts
src/lib/getLanguageIdByRoute.ts
src/lib/getNumberedStaticPaths.ts
src/lib/getValidLanguage.ts
src/lib/test/helpers.tsx
src/lib/time.ts
src/lib/useQueryString.ts
src/pages/[language]/books/[id]/feed.xml/index.ts

Scope lodash imports

---

public/apple-app-site-association
src/components/molecules/downloadAppButton.tsx
src/components/molecules/player.module.scss
src/components/molecules/player.tsx
src/components/organisms/navigation.module.scss
src/components/organisms/navigation.tsx
src/containers/base.tsx
src/containers/home.tsx
src/lib/getNavigationItems.tsx

Fixes https://trello.com/c/S82AU9xa/213-no-hover-on-full-screen-icon, ~https://trello.com/c/sE79gm3v/212-universal-links-not-working~, https://trello.com/c/DIlsiABb/211-fix-player-icons-on-mobile.

Fix some visual issues

---

next.config.js
src/__mocks__/@material-ui/core/Slider.tsx
src/components/HOCs/withAuthGuard.tsx
src/components/molecules/dropdown.tsx
src/components/molecules/login.tsx
src/components/molecules/recordingButtonFavorite.tsx
src/components/molecules/searchBar.module.scss
src/components/molecules/searchBar.tsx
src/components/molecules/teaseRecording.tsx
src/components/organisms/modal.tsx
src/components/templates/andGlobalModals.tsx
src/components/templates/andMiniplayer.tsx
src/containers/account/profile.spec.tsx
src/containers/account/profile.tsx
src/containers/account/reset.tsx
src/containers/library/history.tsx
src/lib/api/collectionFavorite.graphql
src/pages/[language]/account/logout.tsx
src/pages/[language]/account/preferences.ts
src/pages/[language]/account/profile.ts
src/pages/[language]/library/history.tsx
src/pages/[language]/library/index.ts
src/pages/[language]/library/playlist/[id].ts
src/pages/[language]/library/playlists.ts
src/pages/[language]/search/collections/page/[i].ts
src/pages/[language]/search/persons/page/[i].ts
src/pages/[language]/search/sequences/page/[i].ts
src/pages/[language]/search/sponsors/page/[i].ts
src/pages/[language]/search/teachings/page/[i].ts
src/styles/styles.scss

Fixes https://trello.com/c/BH9UWD5U/216-perf-nix-material-ui, refs https://trello.com/c/x8USKAuu/116-performance-audit-new-site.

Lazyload MUI, no message parser, split modules

---

.graphqlrc.yml
graphql-plugin-react-query.js
src/lib/api/fetchApi.spec.ts
src/lib/api/fetchApi.ts
src/lib/generated/graphql.ts

Use custom react-query plugin to nix client-side gql parsing

---

src/components/organisms/miniplayer.tsx
src/components/templates/andPlaybackContext.tsx
src/containers/base.tsx
src/lib/usePlaybackSession.tsx

Skip global videojs css, skip unused requests

---

src/containers/base.tsx

Fixes https://trello.com/c/G5afQijh/227-ensure-weve-given-fontawesome-proper-attribution-or-otherwise-have-proper-license.

Hackfix for FA attribution

---

src/components/organisms/navigation.module.scss

Fixes https://trello.com/c/GVLt9uO4/232-cant-access-user-link-at-bottom-of-nav-drawer-on-small-mobile.

Fix missing navigation user link on mobile

---

src/containers/discover/collections.graphql
src/containers/discover/collections.tsx
src/lib/generated/graphql.ts
src/pages/[language]/discover/collections.ts

Fixes https://trello.com/c/OrWlOlJK/214-update-discover-collections-featured-collection.

Update featured collection

---

public/compiled-lang/en.json
public/lang/en.json
src/components/molecules/buttonDownload.tsx
src/components/templates/andNavigation.tsx
src/containers/about.module.scss
src/lib/getNavigationItems.tsx

Fixes two email issues from Alistair

Fix more bugs

---

src/containers/story/albums/list.spec.tsx
src/lib/getPaginatedStaticProps.ts

Throw 404 for invalid language slugs

---

src/pages/api/download/[[...slugs]].ts

Fixes https://trello.com/c/LAyX7w8F/251-redirector-encode-uri-components.

Encode redirector URI components

---

src/components/HOCs/withIntl.spec.tsx
src/components/atoms/headingBase.module.scss
src/components/atoms/progressBar.tsx
src/components/molecules/mininav.module.scss
src/containers/presenter/list.tsx
src/containers/sponsor/list.tsx
src/styles/common.scss
src/styles/mixins.scss
src/styles/styles.scss

Only load variable font for browsers that support it:
Before:
After:
Also fixes https://trello.com/c/3ilmtGGZ/243-mobile-video-not-seekable-with-drag-bar, https://trello.com/c/1Srz7TcL/256-small-caps-letters-still-tripping-up-alphabetical-list-pages.

Fixes and improvements

---

public/compiled-lang/es.json
public/compiled-lang/fr.json
public/lang/es.json
public/lang/fr.json

Included in an email from Seidy.

Tweak french langs

---

src/components/molecules/socialLogin.tsx

Refs and hopefully fixes https://trello.com/c/clIZgWvm/248-facebook-login-giving-client-error.

Attempt to fix FB login issues on mobile

---

src/containers/home.spec.tsx
src/containers/sermon/list.all.spec.tsx
src/containers/testimonies.spec.tsx
src/lib/constants.ts

Slack from Alistair about published content not appearing within an hour.

Reduce TTL to 1hr

---

src/components/organisms/slider.module.scss
src/components/organisms/slider.tsx

Fixes https://youtu.be/p2SIkAy2qDw?t=210, https://trello.com/c/pRLZALBz/274-make-the-slide-indicator-dots-in-all-the-carousels-clickable.

Fix floating controls slider links not functioning

---

schema.graphql
src/components/molecules/buttonDownload.graphql
src/components/templates/andMiniplayer.graphql
src/lib/generateFeed.graphql
src/lib/generated/graphql.ts

Fixes https://trello.com/c/34vBIAAa/264-rss-doesnt-use-rss-enclosure-links.

Set media file url request types

---

public/compiled-lang/en.json
public/lang/en.json
src/components/atoms/progressBar.module.scss
src/components/molecules/buttonGuest.module.scss
src/components/molecules/buttonGuest.tsx
src/components/molecules/login.module.scss
src/components/organisms/navigation.tsx
src/components/organisms/recording.module.scss
src/components/organisms/recording.tsx
src/containers/account/register.spec.tsx
src/containers/discover.tsx

Fixes https://trello.com/c/KyBzZfBm/281-scrubber-z-index-broken, https://trello.com/c/UdWqeheU/283-show-no-name-for-users-without-a-name, https://trello.com/c/aBJmh6zG/174-fade-both-sides-of-scrollable-element, https://trello.com/c/YaDY5GR9/188-update-cta-on-discover-from-see-all-recent-teachings-to-see-all-teachings, https://trello.com/c/VRAvOQyo/176-no-exit-button-link-on-login-register-pages.

Fixes and tweaks

---

audit-ci.json
src/components/templates/andMiniplayer.graphql
src/components/templates/andPlaybackContext.tsx
src/containers/release/detail.tsx
src/containers/sermon/detail.spec.tsx
src/lib/generated/graphql.ts

Fixes https://trello.com/c/LmAF3OJU/285-implement-cdn-url-logging. Another source of missing downloads... 😒

Log stream plays

---

public/compiled-lang/de.json
public/compiled-lang/en.json
public/lang/de.json
public/lang/en.json
src/components/HOCs/withIntl.spec.tsx
src/containers/home.graphql
src/containers/home.module.scss
src/containers/home.spec.tsx
src/containers/home.tsx
src/lib/generated/graphql.ts

Fixes several T&S board cards.

Home page updates from Ivan

---

src/components/molecules/login.tsx
src/components/molecules/socialLogin.tsx
src/containers/account/login.tsx
src/containers/account/loginRedirect.tsx
src/containers/account/register.spec.tsx
src/containers/account/register.tsx

Refs https://trello.com/c/5JQDMJDu/282-google-oauth-flow-doesnt-work-well.

Improve Google OAuth login/register flow

---

audit-ci.json
public/compiled-lang/en.json
public/lang/en.json
src/components/molecules/card/hat/audiobook.tsx
src/components/molecules/card/hat/sponsor.graphql
src/components/molecules/card/hat/sponsor.module.scss
src/components/molecules/card/hat/sponsor.tsx
src/components/molecules/card/recording.graphql
src/components/molecules/card/recording.tsx
src/components/molecules/card/recordingStack.graphql
src/components/molecules/card/recordingStack.tsx
src/components/molecules/card/sermon.tsx
src/components/molecules/teaseRecording.tsx
src/containers/home.module.scss
src/containers/home.tsx
src/containers/library/loggedOut.tsx
src/containers/sponsor/detail.tsx
src/lib/generated/graphql.ts

Fixes https://trello.com/c/ecv3qIRT/186-rework-library-auth-wall-copy, https://trello.com/c/Fl7eTvwt/191-adjust-homepage-hero-image-to-allow-for-button-above-fold-169, https://trello.com/c/caVKIbVQ/195-look-at-single-hats.

Visual tweaks from Ivan

---

audit-ci.json
src/components/organisms/sequence.tsx

Hide sponsor hat on series detail page

---

public/compiled-lang/en.json
public/lang/en.json
src/components/HOCs/withIntl.spec.tsx
src/components/organisms/recording.graphql
src/components/organisms/recording.tsx
src/containers/base.media.spec.tsx
src/containers/sermon/detail.spec.tsx
src/containers/story/detail.spec.tsx
src/lib/generated/graphql.ts

Refs https://trello.com/c/wNAr14Hn/277-add-open-graph-json-ld-tags and Slack request.

First pass at basic OpenGraph tags

---

next.config.js
src/components/templates/andPlaybackContext.tsx

Fixes https://trello.com/c/NGIFHBu4/239-lazyload-videojs-for-bundle-size.

Lazyload Video.js bundle for smaller app bundle

---

src/components/HOCs/withAuthGuard.spec.tsx
src/components/HOCs/withIntl.spec.tsx
src/components/molecules/buttonGuest.tsx
src/components/molecules/login.spec.tsx
src/components/molecules/login.tsx
src/components/organisms/navigation.tsx
src/containers/account/loginRedirect.tsx
src/containers/account/profile.spec.tsx
src/containers/account/register.tsx
src/containers/library/loggedOut.tsx
src/lib/routes.ts

Fixes https://trello.com/c/O2Z8Bu9j/253-login-doesnt-return-you-to-the-page-you-were-on-previously.

On login/register redirect back to previous page

---

src/components/molecules/form/checkbox.tsx
src/containers/account/playlists.tsx
src/containers/account/profile.graphql
src/containers/account/profile.module.scss
src/containers/account/profile.tsx
src/lib/generated/graphql.ts

Fixes https://trello.com/c/UrBJhrry/286-delete-account-button-on-profile-page-doesnt-seem-to-do-anything.

Delete account flow

---

src/components/molecules/loginForm.tsx
src/lib/api/login.graphql
src/lib/api/login.ts
src/lib/generated/graphql.ts

Depends on https://github.com/avorg/audioverse-graphql/pull/526 and fixes https://trello.com/c/EObdnjba/300-let-user-know-if-email-does-not-exist.

Improve login error messages

---

src/components/atoms/progressBar.tsx
src/components/molecules/playbackTimes.module.scss
src/components/molecules/player.spec.tsx
src/components/molecules/player.tsx
src/components/organisms/miniplayer.module.scss
src/components/organisms/recording.module.scss
src/components/templates/andPlaybackContext.tsx
src/lib/test/helpers.tsx

Fixes https://trello.com/c/1t2S8og8/306-speed-is-lost-when-recording-advances-in-playlist, https://trello.com/c/9HwK20Jq/301-audio-stutters-when-seeking, https://trello.com/c/7gXEEJc1/201-miniplayer-bar-jumping.

Fix several playback bugs

---

src/components/molecules/card/sponsor.graphql
src/containers/sponsor/detail.graphql
src/lib/generated/graphql.ts

Refs https://github.com/avorg/audioverse-graphql/pull/531.

Remove unnecessary query filter

---

src/components/atoms/progressBar.module.scss
src/components/atoms/progressBar.tsx
src/components/molecules/player.tsx

Before:
https://user-images.githubusercontent.com/120155/156626718-94a4f5cf-5f91-467b-94ef-82574a0afecb.mov
After:
https://user-images.githubusercontent.com/120155/156626733-3442b8ce-a43e-4516-9641-40b168026d22.mov

Fix progress indicator jumping on Safari

---

next.config.js

Refs https://trello.com/c/Zd3kxm2Z/324-users-unable-to-access-account-or-reset-password.

Redirect legacy reset password to account login

---

next.config.js

Discovered during GA sleuthing

Fix broken Bible redirects

---

src/components/molecules/player.tsx
src/lib/useGlobalSpaceDown.ts

Created a react hook that captures space key press action globally.

Allow spacebar play/stop on video player

---

public/compiled-lang/en.json
public/lang/en.json
src/containers/discover.graphql
src/containers/discover.spec.tsx
src/containers/discover.tsx
src/lib/generated/graphql.ts
src/pages/[language]/discover/index.ts

Add Featured Teachings to Discover page

---

src/components/molecules/card/favoriteEntity.tsx
src/containers/discover/collections.tsx

Fixes [this](https://www.audioverse.org/en/discover/collections):

Fix featured sequence collection

---

src/components/molecules/card/sequence.module.scss
src/components/organisms/recording.tsx

Hide transcripts for audiobooks

---

public/apple-app-site-association

Refs https://trello.com/c/yJMt2cue/98-handle-universal-links.

Update AASA for new site/app

---

src/components/molecules/buttonPlay.tsx
src/components/molecules/card/bibleVersion.module.scss
src/components/molecules/card/bibleVersion.tsx

Fix favorite icon color on Bible cards

---

lang-update-mobile.js

This allows reusing the existing translations. Refs https://github.com/avorg/audioverse-mobile/pull/136.

Script to update mobile langs from website langs

---

src/components/molecules/navItem.tsx
src/components/molecules/player.spec.tsx
src/containers/page/detail.graphql
src/containers/page/detail.spec.ts
src/containers/page/detail.tsx
src/lib/generated/graphql.ts
src/pages/[language]/page/[id]/[[...slugs]].ts

This allows us to create custom pages through the admin dashboard. I decided to add it because we need a custom landing page for when users complete the opt-in process for the newsletter.

add custom pages route

---

src/containers/discover/collections.tsx

Corresponds to changes in https://github.com/avorg/audioverse-mobile/pull/159.

Move audiobooks up on the collections page

---

next.config.js

generic qr redirect

---

next.config.js

Fixes https://trello.com/c/8WqLXELa/410-good-morning-nathan-re-alistairs-request-on-https-wwwaudioverseorg-en-give-is-this-something-you-could-help-us-with-this-week-ed.

Add redirect for /give

---

public/compiled-lang/de.json
public/compiled-lang/en.json
public/compiled-lang/es.json
public/compiled-lang/fr.json
public/compiled-lang/ja.json
public/compiled-lang/ru.json
public/compiled-lang/zh.json
public/lang/de.json
public/lang/en.json
public/lang/es.json
public/lang/fr.json
public/lang/ja.json
public/lang/ru.json
public/lang/zh.json
src/components/organisms/libraryNav.tsx
src/lib/useNavigationItems.tsx

Fixes https://trello.com/c/9f5GNhg1/429-aesthetic-parity-for-menu-on-desktop-version.

Rename Library Saved label to Listen Later

---

src/containers/contact.tsx

https://trello.com/c/jrFxbyei/313-link-to-help-portal-in-contact-form

add help link to contact form

---

src/components/molecules/helpWidget.spec.tsx
src/components/molecules/helpWidget.tsx
src/types/window.d.ts

This is a fix for our integration with HelpScout.

trigger beacon suggestions on all route changes

---

src/containers/sermon/embed.module.scss
src/containers/sermon/embed.tsx

https://trello.com/c/BAQX6ofQ/431-allow-more-space-for-oembed-media-titles

allow more space for oembed media titles

---

.github/workflows/nextjs_bundle_analysis.yml

Ref: https://github.com/peter-evans/create-or-update-comment/issues/103#issuecomment-1041057863

request PR write access to fix dependabot checks

---

public/compiled-lang/en.json
public/lang/en.json
src/containers/base.media.spec.tsx
src/containers/give.tsx

Removed amazon smile blurb from donate page and horizontal rule.

AV-98 Removed amazon smile blurb from donate page

---

.github/workflows/ci.yml

Adds a GitHub Actions check that fails if translation strings have not been updated.
Story: https://audioverse7.atlassian.net/jira/software/projects/AV/boards/3?assignee=5e8c0aa21c07ed0b7ddc59e2&selectedIssue=AV-170

add intl ci check

---

public/compiled-lang/pt.json
public/lang/pt.json

Story: https://audioverse7.atlassian.net/jira/software/projects/AV/boards/3?selectedIssue=AV-106

AV-106: Upload pt.json to designated folder on GitHub

---

src/components/molecules/buttonPlayback.tsx
src/components/organisms/drawer.module.scss
src/components/organisms/drawer.tsx
src/components/organisms/mobileHeader.module.scss
src/components/organisms/mobileHeader.tsx
src/components/templates/andNavigation.module.scss
src/components/templates/andNavigation.tsx
src/lib/date.ts

This PR extracts most of the code in the AndNavigation component to separate components in order to make the AndNavigation component easier to modify.
Jira story: https://audioverse7.atlassian.net/jira/software/projects/AV/boards/3?selectedIssue=AV-243&text=refactor

Refactor AndNavigation component

---

public/compiled-lang/pt.json
public/lang/pt.json

This PR adds some Portuguese translations for the new search interface.
Story comment: https://audioverse7.atlassian.net/browse/AV-250?focusedCommentId=10219&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-10219

PT translations from @jperegrino75

---

next.config.js

Card: https://audioverse7.atlassian.net/jira/software/projects/AV/boards/3?selectedIssue=AV-349

fix trending teachings link

---

src/components/atoms/circleInitials.module.scss
src/components/atoms/circleInitials.tsx
src/components/molecules/card/person.tsx
src/containers/presenter/list/list.tsx

I have updated person.tsx and added a component to create the initial circle

Av 518 presenters with no images to display first letter of first and last name presenter s card on website and mobile browser

---

public/compiled-lang/en.json
public/lang/en.json
src/components/atoms/scrollToTop.tsx
src/components/molecules/card/sequence.tsx
src/components/organisms/cardSlider/section/egwAudiobooks.tsx
src/components/organisms/searchResults.filters.tsx
src/components/organisms/searchResults.graphql
src/components/organisms/searchResults.useResults.tsx
src/components/templates/andNavigation.tsx
src/containers/audiobook/egwList.tsx
src/containers/discover/index.tsx
src/lib/useNavigationItems.tsx
src/pages/[language]/egwbooks/page/[i].tsx

I ended up adding a Ellen G. White section for the search results.

Av 663 not filtering by audio book on egw browse page

---

src/components/molecules/card/hat/bibleBook.tsx
src/components/molecules/card/sequence.tsx
src/containers/home.spec.tsx

Fixed the issues of AV-1010 by fixing data in Bible Bulk Uploader, however, there were some titles that showed KJV for World English Bible. Fixed this and made the whole Bible Version (Conference Title) show.

Av 1010 fix bible initials

---

src/components/organisms/recording.tsx
src/components/templates/andMiniplayer.spec.tsx
src/components/templates/andPlaybackContext.tsx
src/lib/usePlaybackSession.tsx

https://audioverse7.atlassian.net/browse/AV-930

fix: tease play

---

src/components/organisms/recording.tsx
src/containers/library/playlist/detail.tsx
src/containers/library/playlist/libraryPlaylistDetail.tsx
src/containers/playlist/item.graphql
src/containers/playlist/item.tsx
src/lib/routes/library.ts
src/lib/useNavigationItems.tsx
src/pages/[language]/library/playlists/[playlist]/index.ts
src/pages/[language]/library/playlists/[playlist]/items/[id]/[[...slugs]].tsx

https://audioverse7.atlassian.net/browse/AV-1163

fix: private playlist

---

package-lock.json
src/components/organisms/navigation.module.scss

https://audioverse7.atlassian.net/jira/software/projects/AV/boards/3?assignee=712020%3Afbf78bba-2174-45a3-bda3-9bd364fbc1ee&selectedIssue=AV-1224

Av 1224 three dotted menu not working on website and mobile browser

---

public/.well-known/assetlinks.json

https://audioverse7.atlassian.net/browse/AV-807

fix: deep links

---

public/compiled-lang/br.json
public/compiled-lang/de.json
public/compiled-lang/en.json
public/compiled-lang/es.json
public/compiled-lang/fr.json
public/compiled-lang/ja.json
public/compiled-lang/ru.json
public/compiled-lang/zh.json
public/lang/br.json
public/lang/de.json
public/lang/en.json
public/lang/es.json
public/lang/fr.json
public/lang/ja.json
public/lang/ru.json
public/lang/zh.json
src/components/atoms/circleInitials.module.scss
src/components/molecules/jumpBar.module.scss
src/components/molecules/jumpBar.tsx
src/containers/presenter/list/all.spec.tsx
src/containers/presenter/list/all.tsx
src/containers/presenter/list/letter.tsx
src/containers/presenter/list/list.module.scss
src/containers/presenter/list/list.tsx

https://audioverse7.atlassian.net/jira/software/projects/AV/boards/3?assignee=712020%3Afbf78bba-2174-45a3-bda3-9bd364fbc1ee&selectedIssue=AV-547

Av 547 update all presenters page on mobile website to better match t s design

---

src/components/organisms/cardSlider/index.tsx

https://audioverse7.atlassian.net/browse/AV-1340

fix: slider

---

next.config.js
src/components/HOCs/withAuthGuard.spec.tsx
src/components/molecules/socialLogin.tsx
src/components/organisms/navigation.tsx
src/components/organisms/profileForm.tsx
src/components/organisms/registerForm.tsx
src/containers/account/register.spec.tsx
src/lib/api/fetchApi.spec.ts
src/lib/api/login.ts
src/lib/api/useLogout.ts
src/lib/cookies.ts
src/lib/test/loadAuthGuardData.ts

https://audioverse7.atlassian.net/browse/AV-1390

feat: add user_id cookie

---

package-lock.json
src/components/organisms/recording.tsx
src/containers/bible/book.spec.tsx
src/containers/bible/book.tsx
src/lib/api/bibleBrain.ts

https://audioverse7.atlassian.net/browse/AV-1447
https://audioverse7.atlassian.net/browse/AV-1453

feat: add GA recording_view event

---

src/services/bibles/constants.ts
src/services/bibles/fcbh/getFcbhBook.ts
src/services/bibles/fcbh/versions.ts
src/services/bibles/getChapter.ts
src/services/bibles/getChapters.ts
src/services/bibles/schemas/book.ts
src/services/bibles/schemas/version.ts
src/services/bibles/transforms/bookTransforms.ts
src/services/bibles/transforms/chapterTransforms.spec.ts
src/services/bibles/transforms/chapterTransforms.ts
src/services/bibles/types.ts

https://audioverse7.atlassian.net/browse/AV-1349

update FCBH Bible tracking URL

---

src/components/molecules/login.tsx
src/components/templates/andAuthGuard.spec.tsx

https://audioverse7.atlassian.net/jira/software/projects/AV/boards/3?assignee=712020%3Afbf78bba-2174-45a3-bda3-9bd364fbc1ee&selectedIssue=AV-1527

added onsuccess to the socialLogin in login.tsx

---

audit-ci.json
src/components/molecules/player/index.tsx

https://audioverse7.atlassian.net/jira/software/projects/AV/boards/3?assignee=712020%3Afbf78bba-2174-45a3-bda3-9bd364fbc1ee&selectedIssue=AV-1404

update prefersAudio to session.prefersAudio

---

src/pages/[language]/conferences/[id]/presenters/[presenterId].tsx

https://audioverse7.atlassian.net/jira/software/projects/AV/boards/3?assignee=712020%3Afbf78bba-2174-45a3-bda3-9bd364fbc1ee&selectedIssue=AV-1441

updated share link on conference person

---

src/lib/hooks/useIsAuthenticated.ts
src/lib/useIntlMessages.ts

https://audioverse7.atlassian.net/jira/software/projects/AV/boards/3?assignee=712020%3Afbf78bba-2174-45a3-bda3-9bd364fbc1ee&selectedIssue=AV-1347

Av 1347 user language change on preferences not being taken into consideration at all website 
