audioverse-org/audioverse-next

.eslintrc.js
.github/workflows/ci.yml
.prettierignore
.prettierrc
lib/api.js
package-lock.json
package.json
pages/[language]/sermons/[id].js
pages/_app.js
pages/api/hello.js
pages/index.js
tsconfig.json

This uses ESLint to auto format the code. Run `npm run lint:fix` to format everything. I didn't run it to avoid merge conflicts with your branch. 
If you use VS Code and install the [ESLint plugin](https://marketplace.visualstudio.com/items?itemName=dbaeumer.vscode-eslint) you can have it auto-fix both lint issues and code formatting (with Prettier) on save:

Add basic Prettier config

---

.github/workflows/ci.yml
package.json

I noticed there were several TypeScript errors on #44, so I thought it would be handy to have a command to see those since it seems NextJS doesn't expose them.

Add check TypeScript command

---

src/components/organisms/recording.tsx

On `/en/stories/16718/08-changed-hearts` fixes:

Fix invalid date error on null recordingDate

---

babel.config.js
babel/disable-nextjs-link-prefetching.js

Fixes https://trello.com/c/MGJdSuNt/140-tune-link-preloading, and (I believe!) https://trello.com/c/vbjAcPN4/95-404-on-non-built-presenter-pages.

Disable non-hover link prefetching across the site

---

.env-sample
src/lib/api/fetchApi.ts

(Hopefully) fixes staging data used client-side on beta.av.org. https://nextjs.org/docs/basic-features/environment-variables#exposing-environment-variables-to-the-browser

Use public environment variable for API URL

---

src/components/atoms/progressBar.module.scss
src/components/atoms/progressBar.tsx
src/components/organisms/recording.module.scss

Fixes https://trello.com/c/hjzukFVT/169-pointer-doesnt-indicate-progress-bar-in-card-is-clickable-but-clicking-opens-recording-confusing.

Disable pointer events for non-interactive progress bar

---

src/components/molecules/buttonShare.tsx

Fixes https://trello.com/c/V75Kn92W/179-is-it-intentional-that-clicking-copy-link-in-the-share-menu-opens-a-new-tab-instead-of-copying-the-link.

Make Copy Link actually copy to clipboard

---

src/containers/sermon/list.tsx

Fixes https://trello.com/c/mxk7WMzC/272-recordings-filter-doesnt-highlight-video-when-its-selected.

Fix incorrect video filter selection

---

src/components/templates/andMiniplayer.tsx

Fixes https://trello.com/c/Oa8nNWMy/271-miniplayer-controls-should-always-be-visible-unless-video-is-playing-in-miniplayer.

Start background video playback in miniplayer

---

next.config.js

Attempt to fix https://trello.com/c/ot17Ug1f/270-android-app-wont-play-the-bible-anymore. This replaces the default permanent status code (`308`) with `301` on the main language slug redirect. The `301` code is supported in basically any client in existence, vs. `308` only being supported in non-legacy clients (hopefully such as Android).

Attempt to fix Bible not playing on Android

---

src/containers/give.tsx

Maybe fixes https://trello.com/c/hH8ziDV5/288-donate-form-cut-off. Donorbox has a JS script that sets the height of the iframe based on which tab is actually showing. This seems to be working in most cases. However perhaps this user has some issue running that JS and increasing the default (fallback) height seems like a potential solution.

Increase fallback donate box height

---

src/components/molecules/card/sequence.tsx

This change matches the Figma designs.
Before:
After:

Hide persons on sequence cards with recordings

---

audit-ci.json
package-lock.json
package.json
src/pages/[language]/bibles/[id]/[book]/[chapter].tsx
src/pages/[language]/bibles/index.tsx
src/pages/[language]/blog/[id]/[[...slugs]].ts
src/pages/[language]/books/[id]/[[...slugs]].tsx
src/pages/[language]/books/tracks/[id]/[[...slugs]].tsx
src/pages/[language]/conferences/[id]/[[...slug]].tsx
src/pages/[language]/embed/media/[id].ts
src/pages/[language]/presenters/[id]/[[...slug]].tsx
src/pages/[language]/presenters/[id]/top.ts
src/pages/[language]/series/[id]/[[...slug]].tsx
src/pages/[language]/songs/[id]/[[...slugs]].ts
src/pages/[language]/songs/albums/[id]/[[...slugs]].tsx
src/pages/[language]/songs/book/[book]/[id]/[[...slugs]].ts
src/pages/[language]/sponsors/[id]/[[...slugs]].tsx
src/pages/[language]/stories/[id]/[[...slugs]].tsx
src/pages/[language]/stories/albums/[id]/[[...slugs]].tsx
src/pages/[language]/teachings/[id]/[[...slug]].ts
src/pages/[language]/teachings/trending/all.ts

The default value of `revalidate` is `false ([ref](https://nextjs.org/docs/api-reference/data-fetching/get-static-props#revalidate)) which would mean that if any API were unavailable when the page was rendered that 404 would be cached indefinitely.
See also https://github.com/vercel/next.js/issues/25907#issuecomment-857267054

Attempt to fix Bible versions list page 404ing

---

src/components/molecules/languageButton.tsx
src/lib/constants.ts

ASI Scandinavia is ready to start adding content, but we're going to wait to link them until they're ready to launch. Refs https://github.com/avorg/audioverse-next/pull/177/commits/27e1181f8a9ae0838f3ccd4b3d1b58f0ba9894ea

Enable ASI Scandinavian route w/o button option

---

src/pages/api/download/[[...slugs]].ts

This allows the mobile app sending the session token as a header instead of as a cookie. Refs .

Fallback to user session token from headers

---

src/components/HOCs/withIntl.spec.tsx
src/components/molecules/namedAvatar.module.scss
src/components/molecules/namedAvatar.tsx
src/components/molecules/sponsorLockup.graphql
src/components/molecules/sponsorLockup.tsx
src/lib/generated/graphql.ts

E.g. here: https://www.audioverse.org/en/conferences/343/adagra-2019-true-success

Nix sponsor fallback image on collection detail

---

src/containers/presenter/list.module.scss

Fixes [this](https://www.audioverse.org/en/presenters):

Fix summary line-height to avoid truncation

---

audit-ci.json

`mpd-parser` and therefore `xmldom` is not used.

Fix audit failure

---

.github/workflows/ci.yml
.github/workflows/e2e.yml

Previously, the Lighthouse check triggered immediately and then waited until the Vercel build succeeded before checking the pages. This could result in timeouts if multiple Vercel builds were queued.
This PR creates a separate E2E workflow that is only triggered once the Vercel deployment has succeeded, thereby making it unnecessary for the Lighthouse check to do any waiting itself.

add e2e workflow

---

audit-ci.json
graphql-codegen/graphql-plugin-prefetch.ts
package-lock.json
package.json
src/components/HOCs/withAuthGuard.spec.tsx
src/components/HOCs/withAuthGuard.tsx
src/components/molecules/player.tsx
src/components/organisms/navigation.tsx
src/containers/library/playlist/libraryPlaylistDetail.tsx
src/containers/sponsor/list/all.graphql
src/containers/sponsor/list/all.tsx
src/lib/api/login.ts
src/lib/hooks/useIsAuthenticated.graphql
src/lib/hooks/useIsAuthenticated.ts
src/lib/test/loadAuthGuardData.ts
src/pages/[language]/discover/index.ts

Jira story: https://audioverse7.atlassian.net/jira/software/projects/AV/boards/3?assignee=712020:e12535da-4ed4-4700-9b40-8821b41cbf9e&selectedIssue=AV-1153

AV-1153: Fix prefetching and hydration

---

src/components/molecules/transcript.tsx

https://audioverse7.atlassian.net/browse/AV-1263

refactor: use paragraph version of the transcript

---

public/compiled-lang/br.json
public/lang/br.json

Updated Portuguese Terms on Website to match the APP

Updated Portuguese Terms on Website

---

src/components/molecules/socialLogin.tsx
src/components/organisms/registerForm.tsx
src/lib/api/login.ts

https://audioverse7.atlassian.net/browse/AV-1390

refactor: remove user id from the GTM data layer

---

audit-ci.json
package-lock.json
src/containers/library/playlist/detail.graphql
src/containers/library/playlist/detail.tsx
src/containers/sponsor/detail.tsx
src/containers/sponsor/teachings.tsx
src/lib/routes/playlists.ts
src/lib/routes/sponsors.ts
src/pages/[language]/playlists/[playlist]/feed.xml/index.ts

https://audioverse7.atlassian.net/browse/AV-915

feat: add playlist RSS
